### ISSUE TITLE
Implement while and do-while

### ISSUE THREAD

**Issue by martinezlucas98** [martinezlucas98/java2cpp#10]
**Implement while and do while**

_Description:_
> The translator has no grammar for the while and do-while loops. These are major features that must be added.
> The followings must be implemented:
> - [x] 1.  while loop grammar
> - [x] 2.  do while loop grammar

**Comment by Shree-Gillorkar** [comment]
/*Syntax -
Entry Control Loop (While) - 
while(condition){
block of statements 
}


Exist Control Loop (Do while)-
do{
block of statements
}while(condition)
*/


**While Loop example - 
#include <stdio.h>
 
int main () {

   /* local variable definition */
   int a = 10;

   /* while loop execution */
   while( a < 20 ) {
      printf("value of a: %d\n", a);
      a++;
   }
 
   return 0;
}


**Do while example:
#include <stdio.h>
int main()
{
	int j=0;
	do
	{
		printf("Value of variable j is: %d\n", j);
		j++;
	}while (j<=3);
	return 0;
}

**Comment by Shree-Gillorkar** [comment]
Hey @martinezlucas98, can you please help me out with this project. I really want to contribute in this project. My technical skills include C, C++, Python & Java. i think i can figure this out. Just need some guidance.

**Comment by martinezlucas98** [comment]
Sure, this is more of a YACC and LEX project than a C, C++, java, but its really simple.

> YACC is a parser generator based on formal grammar notation similar to BNF; and LEX  generates lexical analyzers.

If you are already familiarized with grammars this should be pretty easy. You could take a look to the [java2cpp.y](https://github.com/martinezlucas98/java2cpp/blob/alpha/java2cpp.y) **<ins>in the alpha branch</ins>** , the nonterminals STATEMENTS and STDIO might be a good example for understanding how it works.

A grammar for the while loop  could be something like: ```WHILE LP EXPRESSION RP LC STATEMENTS RC SEMICOLON```

You could read the tokens meanings at [TOKENS.md](https://github.com/martinezlucas98/java2cpp/blob/alpha/TOKENS.md), this tokens are defined in [java2cpp.l](https://github.com/martinezlucas98/java2cpp/blob/alpha/java2cpp.l).

**Comment by martinezlucas98** [comment]
If you are interested I can assign you this issue and feel free to submit a PR whenever you feel like! :+1:

**Comment by Shree-Gillorkar** [comment]
Thank you, that's so nice of you. I will go through the project and try to figure this out, and if felt something to discuss i will report you.

**Comment by Shree-Gillorkar** [comment]
@martinezlucas98, I added grammar for while loop and also added printf grammar for "do". Please have a look and suggest if any changes are required. Thank you.

**Comment by martinezlucas98** [comment]
@Shree-Gillorkar 
Great!! Just make a pull request to our alpha branch and I will take a look at it as soon as I can.

**Comment by Shree-Gillorkar** [comment]
@martinezlucas98 ya sure, thank you!

**Comment by martinezlucas98** [comment]
Hey @Shree-Gillorkar sorry for the delay, your PR looks pretty good! It just needs a few changes which I mention on your PR. Once you make those changes everything will be good to merge. :+1:

**Comment by Shree-Gillorkar** [comment]
Hey, *@Lucas Martinez*,  It's okay. Hope you are doing quite well. This is
my 1st open source project on which I am working. I would like to thank you
for encouraging and supporting me in knowing this world of open source
contributors. I made the changes you suggested. Hope I can solve the issue
and lend you a helping hand in this project.

**Comment by martinezlucas98** [comment]
Perfect!! Thank you for your help @Shree-Gillorkar
