### ISSUE TITLE
Implement  declaration of array

### ISSUE THREAD

**Issue by Joaquinecc** [martinezlucas98/java2cpp#11]
Required support for Java declarations:
- [x] double[ ] arr1 = new int[5];
- [x] int[ ] arr2 = {5,4,3,2,1}; 
- [x] double[ ][ ] arr3 = new int[3][5]; 
- [x] int[ ][ ] arr4 = {{1,2,3},{4,5,6},{7,8,9}};

**Comment by martinezlucas98** [comment]
Commits:
[9b67da2de981a48fec97818f04492dbe227dbad7](https://github.com/martinezlucas98/java2cpp/commit/9b67da2de981a48fec97818f04492dbe227dbad7)
[e46927802b3274a949e2df7d3a9bfc2562b990b8](https://github.com/martinezlucas98/java2cpp/commit/e46927802b3274a949e2df7d3a9bfc2562b990b8)
