### ISSUE TITLE
Text input function grammar

### ISSUE THREAD

**Issue by martinezlucas98** [martinezlucas98/java2cpp#19]
**Text input function grammar**

_Description:_
> The following translations are needed and must be added:
> - [ ]  ```Scanner my_input = new Scanner(System.in);```  -----> ```string my_input; std::cin >> my_input;```
> - [ ]  ```my_input = new Scanner(System.in);```  -----> ```std::cin >> my_input;```

**Comment by Shree-Gillorkar** [comment]
@martinezlucas98, Can I know in which file this translations are needed?

**Comment by martinezlucas98** [comment]
Sure @Shree-Gillorkar, java2cpp.l and java.2cpp.y
Pretty much like the do-while one you made.
I think an excellent example for this will be the PRINT or PRINTLN tokens.
I would put these input grammar inside of STDIO as PRINT and PRINTLN.

**Comment by Shree-Gillorkar** [comment]
Okay, I will look into this & will try to solve the issue.

**Comment by Shree-Gillorkar** [comment]
@martinezlucas98, I added Grammar for  my_input & Scanner object in java2cpp.y,
and also added token for System.in and scanner in java2cpp.l. 
I am a bit confused about the code I wrote, Can you please check my code and let me know if any changes are required.

**Comment by martinezlucas98** [comment]
@Shree-Gillorkar Sure! I'll give you some feedback as soon as I test it.

**Comment by Shree-Gillorkar** [comment]
Ya Sure!

**Comment by martinezlucas98** [comment]
:+1:
