### ISSUE TITLE
Implement Type Error

### ISSUE THREAD

**Issue by martinezlucas98** [martinezlucas98/java2cpp#25]
**Implement Type Error**

_Description:_
An error message must be printed when a type error occurs.
For now we will implement **Panic-Mode Error Recovery.** This can be upgraded in the future.

**Comment by Shree-Gillorkar** [comment]
@martinezlucas98 , may i look into this issue. Can you please tell more detail about it like where the error is detected and which files to be refereed to solve this issue.

**Comment by martinezlucas98** [comment]
@ Shree-Gillorkar right now I am looking at and testing a PR that someone made for problem #26 which I think is necessary before we can try to solve this one (although I could be wrong).
> Anyway, the idea here is to do type conversions (and implicit conversion) and check type compatibility when declaring a variable -right and left sides - (also an implicit conversion, I think)

But I will let you know as soon as the PR I mentioned is merged and if this issue has not been resolved in that same PR.
Anyway, thanks for your interest!

**Comment by Shree-Gillorkar** [comment]
@martinezlucas98 ya its all okay. Let me know whenever you complete that PR you talked about.
